# Generated by Django 5.2.5 on 2025-08-22 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bot", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="telegramuser",
            name="user_id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
