# Generated by Django 5.2.5 on 2025-08-20 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bot", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="event",
            name="id",
        ),
        migrations.AddField(
            model_name="event",
            name="event_id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
