# Generated by Django 5.2.5 on 2025-09-11 11:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bot", "0002_alter_telegramuser_user_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="public",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="event",
            name="tg_id",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="tg_id_event",
                to="bot.telegramuser",
            ),
            preserve_default=False,
        ),
    ]
