# Generated by Django 5.2.5 on 2025-08-20 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bot", "0002_remove_event_id_event_event_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="appointment",
            name="id",
        ),
        migrations.AddField(
            model_name="appointment",
            name="appo_id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
