# Generated by Django 5.2.5 on 2025-08-21 09:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bot", "0003_remove_appointment_id_appointment_appo_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="appointment",
            name="event",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="event",
                to="bot.event",
            ),
        ),
    ]
