# Generated by Django 5.2.5 on 2025-09-12 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bot", "0003_event_public_event_tg_id"),
    ]

    operations = [
        migrations.RenameField(
            model_name="event",
            old_name="tg_id",
            new_name="telegram_user",
        ),
    ]
