# Generated by Django 5.2.5 on 2025-08-21 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bot", "0004_alter_appointment_event"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="telegramuser",
            name="id",
        ),
        migrations.AddField(
            model_name="telegramuser",
            name="user_id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
